# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origendatos',
            name='id_referencia',
            field=models.BigIntegerField(),
        ),
    ]
