# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170916_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localorigendatos',
            name='origen',
        ),
        migrations.AddField(
            model_name='origendatos',
            name='id_referencia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='origen_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrigenDatos'),
        ),
        migrations.DeleteModel(
            name='LocalOrigenDatos',
        ),
    ]
